/* pairing.js is generated by the desktop application on its first launch. */
importScripts("pairing.js");
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({ id: "content-mover", title: "内容迁移", contexts: ["selection"] });
});
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId !== "content-mover") return;
  let text = info.selectionText || "";
  let fidelity = "浏览器右键菜单提供的文本（该页面未允许读取完整选区，请核对换行）";
  try {
    const result = await chrome.scripting.executeScript({
      target: { tabId: tab.id, frameIds: [info.frameId || 0] },
      func: () => {
        const element = document.activeElement;
        if (element && ["TEXTAREA", "INPUT"].includes(element.tagName) &&
            typeof element.selectionStart === "number" && element.selectionStart !== element.selectionEnd) {
          return element.value.slice(element.selectionStart, element.selectionEnd);
        }
        return window.getSelection()?.toString() || "";
      }
    });
    if (result[0]?.result) { text = result[0].result; fidelity = "网页选区原文"; }
  } catch (_) { /* Restricted pages use the context menu's selectionText. */ }
  try {
    const response = await fetch("http://127.0.0.1:19339/capture", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": "Bearer " + CONTENT_MOVER_TOKEN },
      body: JSON.stringify({ text, title: tab.title || "网页", url: info.pageUrl || tab.url || "",
        frameUrl: info.frameUrl || "", fidelity })
    });
    if (!response.ok) throw new Error("本地工具返回 " + response.status);
  } catch (error) {
    chrome.notifications.create({ type: "basic", iconUrl: "icon.png", title: "内容迁移未完成",
      message: "请先启动电脑上的内容迁移工具，再试一次。" + error.message });
  }
});
