package com.contentmover.mobile;
import android.app.*;import android.app.job.*;import android.content.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
  EditText title,text,note,source;TextView status,pictures;Button send;LinearLayout gallery;CheckBox shrink;int previewVersion;ArrayList<Uri> incoming=new ArrayList<>();volatile boolean busy;boolean shared;
  int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  TextView label(LinearLayout root,String value){TextView view=new TextView(this);view.setText(value);view.setTextSize(16);view.setPadding(0,dp(12),0,dp(6));root.addView(view);return view;}
  EditText field(LinearLayout root,String hint,int lines){EditText view=new EditText(this);view.setHint(hint);view.setTextSize(16);view.setMinLines(lines);view.setGravity(Gravity.TOP);if(lines==1)view.setSingleLine(true);root.addView(view,new LinearLayout.LayoutParams(-1,-2));return view;}
  Button button(LinearLayout root,String value,Runnable action){Button view=new Button(this);view.setText(value);root.addView(view,new LinearLayout.LayoutParams(-1,dp(48)));view.setOnClickListener(v->{if(!busy)action.run();});return view;}
  @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().setStatusBarColor(0xff2159a5);ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(dp(22),dp(26),dp(22),dp(26));root.setBackgroundColor(0xfff7f9fc);scroll.addView(root);setContentView(scroll);scroll.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});label(root,"内容迁移 · 手机 → 电脑").setTextSize(25);label(root,"连接同一 Wi-Fi，电脑开启“手机连接”。");button(root,"扫码连接电脑",()->startActivityForResult(new Intent(this,ScanActivity.class),10));status=label(root,"");label(root,"标题");title=field(root,"手机摘录",1);label(root,"原文");text=field(root,"选中文字后分享，也可在这里粘贴",4);label(root,"备注（支持 Markdown）");note=field(root,"为什么保存这段内容？",3);label(root,"出处（可选）");source=field(root,"网页链接或来源名称",1);pictures=label(root,"没有图片");gallery=new LinearLayout(this);gallery.setOrientation(1);root.addView(gallery);shrink=new CheckBox(this);shrink.setText("缩小图片再发送（最长边 2560，JPEG 画质 90%）");root.addView(shrink);label(root,"默认保留原图。大图可勾选缩小；缩小会降低分辨率与画质。").setTextSize(13);button(root,"添加截图 / 图片",()->{Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.setType("image/*");intent.addCategory(Intent.CATEGORY_OPENABLE);intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(intent,11);});send=button(root,"保存并发送到电脑",()->saveAndSend());button(root,"重试待发送内容",()->retry());label(root,"电脑未连接时，内容会先保存在手机。\n最多 10 张图、图片合计 16 MB；文字不会自动改写。\n文件按电脑收到内容的日期归档。").setTextSize(13);
    Intent intent=getIntent();String action=intent.getAction();shared=Intent.ACTION_PROCESS_TEXT.equals(action) || Intent.ACTION_SEND.equals(action) || Intent.ACTION_SEND_MULTIPLE.equals(action);CharSequence selected=Intent.ACTION_PROCESS_TEXT.equals(action)?intent.getCharSequenceExtra(Intent.EXTRA_PROCESS_TEXT):intent.getCharSequenceExtra(Intent.EXTRA_TEXT);if(selected!=null)text.setText(selected);CharSequence givenTitle=intent.getCharSequenceExtra(Intent.EXTRA_SUBJECT);if(givenTitle==null)givenTitle=intent.getCharSequenceExtra(Intent.EXTRA_TITLE);if(givenTitle!=null)title.setText(givenTitle);if(Intent.ACTION_SEND.equals(action)){Uri image=intent.getParcelableExtra(Intent.EXTRA_STREAM);if(image!=null)incoming.add(image);}if(Intent.ACTION_SEND_MULTIPLE.equals(action)){ArrayList<Uri> list=intent.getParcelableArrayListExtra(Intent.EXTRA_STREAM);if(list!=null)incoming.addAll(list);}if(saved!=null){title.setText(saved.getString("title"));text.setText(saved.getString("text"));note.setText(saved.getString("note"));source.setText(saved.getString("source"));ArrayList<Uri> restored=saved.getParcelableArrayList("images");if(restored!=null)incoming=restored;shrink.setChecked(saved.getBoolean("shrink"));}update();
  }
  void update(){showImages();pictures.setText(incoming.size()+" 张图片，将按添加顺序保存");String host=getSharedPreferences("pair",0).getString("host","");status.setText((host.isEmpty()?"尚未配对电脑":"电脑："+host)+"\n待发送："+Transfer.pending(this).length+" 条");}
  @Override protected void onResume(){super.onResume();if(status!=null)update();}
  @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putString("title",title.getText().toString());state.putString("text",text.getText().toString());state.putString("note",note.getText().toString());state.putString("source",source.getText().toString());state.putParcelableArrayList("images",incoming);state.putBoolean("shrink",shrink.isChecked());}
  @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK || data==null)return;if(request==10){try{Transfer.pair(this,data.getStringExtra("pair"));update();Toast.makeText(this,"配对已保存，可以发送内容",Toast.LENGTH_SHORT).show();}catch(Exception e){message(e.getMessage());}}if(request==11){if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)incoming.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)incoming.add(data.getData());if(incoming.size()>10){incoming=new ArrayList<>(incoming.subList(0,10));message("最多添加 10 张图片");}update();}}
  void schedule(){JobInfo job=new JobInfo.Builder(47831,new ComponentName(this,SendJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_UNMETERED).setBackoffCriteria(30000,JobInfo.BACKOFF_POLICY_EXPONENTIAL).build();((JobScheduler)getSystemService(JOB_SCHEDULER_SERVICE)).schedule(job);}
  void saveAndSend(){if(busy)return;if(text.getText().toString().trim().isEmpty() && incoming.isEmpty()){message("请填写文字或添加图片");return;}if(incoming.size()>10){message("最多 10 张图片");return;}final String original=text.getText().toString(),heading=title.getText().toString(),remark=note.getText().toString(),origin=source.getText().toString();final boolean optimize=shrink.isChecked();final ArrayList<Uri> images=new ArrayList<>(incoming);busy=true;setInputsEnabled(false);status.setText("正在保存到手机…");new Thread(()->{boolean queued=false;try{if(original.length()>200000 || remark.length()>200000 || heading.length()>1000 || origin.length()>4000)throw new IOException("文字过长");JSONObject clip=new JSONObject().put("Id",UUID.randomUUID().toString().replace("-","")).put("Text",original).put("Title",heading).put("Note",remark).put("Source",origin);JSONArray attachments=new JSONArray();long total=0;for(int i=0;i<images.size();i++){byte[] bytes=ImageAttachments.prepare(this,images.get(i),optimize,i+1);total+=bytes.length;if(total>ImageAttachments.TOTAL_LIMIT)throw new IOException("图片合计 "+ImageAttachments.size(total)+"，超过 16 MB。请勾选缩小或移除部分图片。");attachments.put(new JSONObject().put("Data",Transfer.encode(bytes)));}clip.put("Images",attachments);Transfer.enqueue(this,clip);queued=true;schedule();final String result=Transfer.sendPending(this);runOnUiThread(()->{text.setText("");note.setText("");incoming.clear();update();message(result);});}catch(Exception | OutOfMemoryError e){final boolean retained=queued;runOnUiThread(()->{if(retained){text.setText("");note.setText("");incoming.clear();update();message("已保存在待发送列表。连接电脑后点重试。\n"+e.getMessage());}else {update();message("尚未保存，原文与图片仍在当前页面。\n"+e.getMessage());}});}finally{runOnUiThread(()->{busy=false;setInputsEnabled(true);});}}).start();}
  void retry(){if(busy)return;busy=true;status.setText("正在连接电脑…");new Thread(()->{try{final String result=Transfer.sendPending(this);runOnUiThread(()->{update();message(result);});}catch(Exception e){schedule();runOnUiThread(()->{update();message("内容仍在待发送列表。请检查电脑开机、同一 Wi-Fi 和防火墙。\n"+e.getMessage());});}finally{runOnUiThread(()->busy=false);}}).start();}
  void setInputsEnabled(boolean enabled){send.setEnabled(enabled);title.setEnabled(enabled);text.setEnabled(enabled);note.setEnabled(enabled);source.setEnabled(enabled);shrink.setEnabled(enabled);}
  void showImages(){
    final int version=++previewVersion;gallery.removeAllViews();
    for(int i=0;i<incoming.size();i++){
      final int index=i;final Uri uri=incoming.get(i);
      LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(0,dp(8),0,dp(8));gallery.addView(card);
      TextView detail=label(card,"第 "+(i+1)+" 张 · 正在读取预览…");
      ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setContentDescription("第 "+(i+1)+" 张图片预览");card.addView(image,new LinearLayout.LayoutParams(-1,dp(160)));
      button(card,"移除这张图片",()->{if(version==previewVersion){incoming.remove(index);update();}});
      new Thread(()->{
        android.graphics.Bitmap bitmap=null;String description;boolean oversized=false;
        try{long bytes=ImageAttachments.sourceSize(this,uri);android.graphics.BitmapFactory.Options info=ImageAttachments.bounds(this,uri);bitmap=ImageAttachments.thumbnail(this,uri);description="第 "+(index+1)+" 张 · "+ImageAttachments.size(bytes)+" · "+info.outWidth+" × "+info.outHeight;oversized=bytes>ImageAttachments.SINGLE_LIMIT || (long)info.outWidth*info.outHeight>24000000;if(oversized)description+="\n原图超限：请勾选缩小或移除";}
        catch(Exception | OutOfMemoryError error){description="第 "+(index+1)+" 张预览失败，请重新选择图片";}
        final android.graphics.Bitmap preview=bitmap;final String infoText=description;final boolean warning=oversized;
        runOnUiThread(()->{if(version!=previewVersion || isDestroyed()){if(preview!=null)preview.recycle();return;}detail.setText(infoText);if(warning)detail.setTextColor(0xffb33a22);if(preview!=null)image.setImageBitmap(preview);});
      }).start();
    }
  }
  @Override protected void onDestroy(){previewVersion++;super.onDestroy();}
  void message(String value){if(isFinishing() || isDestroyed())return;new AlertDialog.Builder(this).setTitle("内容迁移").setMessage(value).setPositiveButton("好",null).show();}
}
