package com.contentmover.mobile;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.hardware.Camera;import android.os.Bundle;import android.view.*;import android.widget.*;import com.google.zxing.*;import com.google.zxing.common.HybridBinarizer;
@SuppressWarnings("deprecation")
public class ScanActivity extends Activity implements SurfaceHolder.Callback,Camera.PreviewCallback {
  Camera camera;SurfaceView preview;volatile boolean decoding,done;long last;
  @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);LinearLayout root=new LinearLayout(this);root.setOrientation(1);TextView help=new TextView(this);help.setText("对准电脑“手机连接”窗口的二维码");help.setTextSize(18);help.setPadding(20,40,20,20);root.addView(help);preview=new SurfaceView(this);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);preview.getHolder().addCallback(this);if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},1);}
  void start(){if(camera!=null || checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED || !preview.getHolder().getSurface().isValid())return;try{camera=Camera.open();camera.setDisplayOrientation(90);Camera.Parameters params=camera.getParameters();java.util.List<String> modes=params.getSupportedFocusModes();if(modes!=null && modes.contains(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE))params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);camera.setParameters(params);camera.setPreviewDisplay(preview.getHolder());camera.setPreviewCallback(this);camera.startPreview();}catch(Exception e){stop();new AlertDialog.Builder(this).setMessage("无法使用相机，请允许相机权限并重试。" ).setPositiveButton("返回",(a,b)->finish()).show();}}
  void stop(){if(camera!=null){camera.setPreviewCallback(null);camera.stopPreview();camera.release();camera=null;}}
  @Override public void surfaceCreated(SurfaceHolder holder){start();}
  @Override public void surfaceChanged(SurfaceHolder holder,int format,int width,int height){}
  @Override public void surfaceDestroyed(SurfaceHolder holder){stop();}
  @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==1 && g.length>0 && g[0]==PackageManager.PERMISSION_GRANTED)start();else finish();}
  @Override protected void onResume(){super.onResume();if(preview!=null)start();}
  @Override protected void onPause(){stop();super.onPause();}
  @Override public void onPreviewFrame(byte[] data,Camera source){if(done || decoding || System.currentTimeMillis()-last<400)return;last=System.currentTimeMillis();decoding=true;Camera.Size size=source.getParameters().getPreviewSize();final byte[] frame=data.clone();new Thread(()->{try{MultiFormatReader reader=new MultiFormatReader();java.util.Map<DecodeHintType,Object> hints=new java.util.EnumMap<>(DecodeHintType.class);hints.put(DecodeHintType.POSSIBLE_FORMATS,java.util.Collections.singletonList(BarcodeFormat.QR_CODE));Result result=reader.decode(new BinaryBitmap(new HybridBinarizer(new PlanarYUVLuminanceSource(frame,size.width,size.height,0,0,size.width,size.height,false))),hints);if(result.getText().startsWith("contentmover://pair?")){done=true;runOnUiThread(()->{setResult(RESULT_OK,new Intent().putExtra("pair",result.getText()));finish();});}}catch(Exception ignored){}finally{decoding=false;}}).start();}
}
