package com.contentmover.mobile;
import android.content.Context;import android.net.Uri;import android.util.Base64;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import javax.crypto.*;import javax.crypto.spec.*;

public final class Transfer {
  static final java.util.concurrent.atomic.AtomicBoolean sending=new java.util.concurrent.atomic.AtomicBoolean();
  static byte[] derive(byte[] key,String purpose)throws Exception{MessageDigest hash=MessageDigest.getInstance("SHA-256");hash.update(key);return hash.digest(purpose.getBytes(StandardCharsets.US_ASCII));}
  static byte[] decode(String value){return Base64.decode(value,Base64.NO_WRAP);}
  static String encode(byte[] value){return Base64.encodeToString(value,Base64.NO_WRAP);}
  static String seal(byte[] key,String text)throws Exception{byte[] iv=new byte[16];new SecureRandom().nextBytes(iv);Cipher aes=Cipher.getInstance("AES/CBC/PKCS5Padding");aes.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(derive(key,"enc"),"AES"),new IvParameterSpec(iv));byte[] data=aes.doFinal(text.getBytes(StandardCharsets.UTF_8));Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(derive(key,"mac"),"HmacSHA256"));mac.update(iv);return new JSONObject().put("iv",encode(iv)).put("data",encode(data)).put("mac",encode(mac.doFinal(data))).toString();}
  static String open(byte[] key,String text)throws Exception{JSONObject env=new JSONObject(text);byte[] iv=decode(env.getString("iv")),data=decode(env.getString("data")),signature=decode(env.getString("mac"));Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(derive(key,"mac"),"HmacSHA256"));mac.update(iv);if(!MessageDigest.isEqual(signature,mac.doFinal(data)))throw new IOException("电脑确认验证失败");Cipher aes=Cipher.getInstance("AES/CBC/PKCS5Padding");aes.init(Cipher.DECRYPT_MODE,new SecretKeySpec(derive(key,"enc"),"AES"),new IvParameterSpec(iv));return new String(aes.doFinal(data),StandardCharsets.UTF_8);}
  static boolean privateHost(String host){return AddressPolicy.local(host);}
  static boolean vpnConnected(Context context){android.net.ConnectivityManager manager=(android.net.ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);if(manager==null)return false;for(android.net.Network network:manager.getAllNetworks()){android.net.NetworkCapabilities caps=manager.getNetworkCapabilities(network);if(caps!=null && caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_VPN))return true;}return false;}
  static void pair(Context context,String value)throws Exception{Uri uri=Uri.parse(value.trim());if(!"contentmover".equals(uri.getScheme()) || !"pair".equals(uri.getHost()) || !"1".equals(uri.getQueryParameter("v")))throw new IOException("不是内容迁移的配对二维码");String host=uri.getQueryParameter("host"),port=uri.getQueryParameter("port"),key=uri.getQueryParameter("key");String mode=uri.getQueryParameter("mode");boolean remote="remote".equals(mode);if((mode!=null && !remote && !"lan".equals(mode)) || !AddressPolicy.allowed(host,remote) || !"47831".equals(port) || decode(key).length!=32)throw new IOException("配对内容无效");context.getSharedPreferences("pair",0).edit().putString("host",host).putString("key",key).putBoolean("remote",remote).apply();}
  static File queue(Context context){File path=new File(context.getFilesDir(),"pending");path.mkdirs();return path;}
  static File[] pending(Context context){File[] files=queue(context).listFiles((dir,name)->name.endsWith(".json"));if(files==null)return new File[0];java.util.Arrays.sort(files,(a,b)->Long.compare(a.lastModified(),b.lastModified()));return files;}
  static byte[] read(InputStream input,int max)throws IOException{ByteArrayOutputStream result=new ByteArrayOutputStream();byte[] bytes=new byte[8192];int count;while((count=input.read(bytes))!=-1){if(result.size()+count>max)throw new IOException("内容过大");result.write(bytes,0,count);}return result.toByteArray();}
  static String enqueue(Context context,JSONObject clip)throws Exception{byte[] serialized=clip.toString().getBytes(StandardCharsets.UTF_8);if(serialized.length>22000000)throw new IOException("本条内容编码后超过传输上限，请减少图片或勾选缩小后重试。");String id=clip.getString("Id");File temp=new File(queue(context),id+".tmp"),destination=new File(queue(context),id+".json");try(FileOutputStream output=new FileOutputStream(temp)){output.write(serialized);output.getFD().sync();}if(!temp.renameTo(destination))throw new IOException("无法保存待发送内容");return id;}
  static String sendPending(Context context)throws Exception{if(!sending.compareAndSet(false,true))return "正在发送，请稍候";try{String host=context.getSharedPreferences("pair",0).getString("host","");boolean remote=context.getSharedPreferences("pair",0).getBoolean("remote",false);if(!AddressPolicy.allowed(host,remote))throw new IOException("请先扫码连接电脑");if(remote && !vpnConnected(context))throw new IOException("远程连接尚未开启。请打开 Tailscale，登录与电脑相同的账号并连接，再点重试。");byte[] key=decode(context.getSharedPreferences("pair",0).getString("key",""));int count=0;for(File file:pending(context)){JSONObject clip;try(FileInputStream input=new FileInputStream(file)){clip=new JSONObject(new String(read(input,22000000),StandardCharsets.UTF_8));}byte[] payload=seal(key,clip.toString()).getBytes(StandardCharsets.UTF_8);HttpURLConnection connection=(HttpURLConnection)new URL("http://"+host+":47831/v1/clips").openConnection();try{connection.setConnectTimeout(remote ? 15000 : 4500);connection.setReadTimeout(remote ? 60000 : 20000);connection.setInstanceFollowRedirects(false);connection.setRequestMethod("POST");connection.setDoOutput(true);connection.setRequestProperty("Content-Type","application/json");connection.setFixedLengthStreamingMode(payload.length);try(OutputStream output=connection.getOutputStream()){output.write(payload);}if(connection.getResponseCode()!=200)throw new IOException("电脑未接受内容，请检查配对或内容大小");String response;try(InputStream input=connection.getInputStream()){response=new String(read(input,65536),StandardCharsets.UTF_8);}JSONObject ack=new JSONObject(open(key,response));if(!ack.optBoolean("saved") || !clip.getString("Id").equals(ack.getString("id")))throw new IOException("保存确认不匹配");if(!file.delete())throw new IOException("无法更新待发送列表");count++;}finally{connection.disconnect();}}return count>0 ? "已保存 "+count+" 条到电脑桌面" : "没有待发送内容";}finally{sending.set(false);}}
}
