package com.contentmover.mobile;
import android.content.Context;import android.net.Uri;import android.util.Base64;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import javax.crypto.*;import javax.crypto.spec.*;

public final class Transfer {
  static final java.util.concurrent.atomic.AtomicBoolean sending=new java.util.concurrent.atomic.AtomicBoolean();
  static byte[] derive(byte[] key,String purpose)throws Exception{MessageDigest hash=MessageDigest.getInstance("SHA-256");hash.update(key);return hash.digest(purpose.getBytes(StandardCharsets.US_ASCII));}
  static byte[] decode(String value){return Base64.decode(value,Base64.NO_WRAP);}
  static String encode(byte[] value){return Base64.encodeToString(value,Base64.NO_WRAP);}
  static String seal(byte[] key,String text)throws Exception{byte[] iv=new byte[16];new SecureRandom().nextBytes(iv);Cipher aes=Cipher.getInstance("AES/CBC/PKCS5Padding");aes.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(derive(key,"enc"),"AES"),new IvParameterSpec(iv));byte[] data=aes.doFinal(text.getBytes(StandardCharsets.UTF_8));Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(derive(key,"mac"),"HmacSHA256"));mac.update(iv);return new JSONObject().put("iv",encode(iv)).put("data",encode(data)).put("mac",encode(mac.doFinal(data))).toString();}
  static String open(byte[] key,String text)throws Exception{JSONObject env=new JSONObject(text);byte[] iv=decode(env.getString("iv")),data=decode(env.getString("data")),signature=decode(env.getString("mac"));Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(derive(key,"mac"),"HmacSHA256"));mac.update(iv);if(!MessageDigest.isEqual(signature,mac.doFinal(data)))throw new IOException("电脑确认验证失败");Cipher aes=Cipher.getInstance("AES/CBC/PKCS5Padding");aes.init(Cipher.DECRYPT_MODE,new SecretKeySpec(derive(key,"enc"),"AES"),new IvParameterSpec(iv));return new String(aes.doFinal(data),StandardCharsets.UTF_8);}
  static boolean privateHost(String host){if(host==null || !host.matches("[0-9]{1,3}(\\.[0-9]{1,3}){3}"))return false;String[] parts=host.split("\\.");int[] a=new int[4];for(int i=0;i<4;i++){a[i]=Integer.parseInt(parts[i]);if(a[i]>255)return false;}return a[0]==10 || (a[0]==172 && a[1]>=16 && a[1]<=31) || (a[0]==192 && a[1]==168) || (a[0]==169 && a[1]==254);}
  static void pair(Context context,String value)throws Exception{Uri uri=Uri.parse(value.trim());if(!"contentmover".equals(uri.getScheme()) || !"pair".equals(uri.getHost()) || !"1".equals(uri.getQueryParameter("v")))throw new IOException("不是内容迁移的配对二维码");String host=uri.getQueryParameter("host"),port=uri.getQueryParameter("port"),key=uri.getQueryParameter("key");if(!privateHost(host) || !"47831".equals(port) || decode(key).length!=32)throw new IOException("配对内容无效");context.getSharedPreferences("pair",0).edit().putString("host",host).putString("key",key).apply();}
  static File queue(Context context){File path=new File(context.getFilesDir(),"pending");path.mkdirs();return path;}
  static File[] pending(Context context){File[] files=queue(context).listFiles((dir,name)->name.endsWith(".json"));if(files==null)return new File[0];java.util.Arrays.sort(files,(a,b)->Long.compare(a.lastModified(),b.lastModified()));return files;}
  static byte[] read(InputStream input,int max)throws IOException{ByteArrayOutputStream result=new ByteArrayOutputStream();byte[] bytes=new byte[8192];int count;while((count=input.read(bytes))!=-1){if(result.size()+count>max)throw new IOException("内容过大");result.write(bytes,0,count);}return result.toByteArray();}
  static String enqueue(Context context,JSONObject clip)throws Exception{String id=clip.getString("Id");File temp=new File(queue(context),id+".tmp"),destination=new File(queue(context),id+".json");try(FileOutputStream output=new FileOutputStream(temp)){output.write(clip.toString().getBytes(StandardCharsets.UTF_8));output.getFD().sync();}if(!temp.renameTo(destination))throw new IOException("无法保存待发送内容");return id;}
  static String sendPending(Context context)throws Exception{if(!sending.compareAndSet(false,true))return "正在发送，请稍候";try{String host=context.getSharedPreferences("pair",0).getString("host","");if(!privateHost(host))throw new IOException("请先扫码连接电脑");byte[] key=decode(context.getSharedPreferences("pair",0).getString("key",""));int count=0;for(File file:pending(context)){JSONObject clip;try(FileInputStream input=new FileInputStream(file)){clip=new JSONObject(new String(read(input,22000000),StandardCharsets.UTF_8));}byte[] payload=seal(key,clip.toString()).getBytes(StandardCharsets.UTF_8);HttpURLConnection connection=(HttpURLConnection)new URL("http://"+host+":47831/v1/clips").openConnection();try{connection.setConnectTimeout(4500);connection.setReadTimeout(20000);connection.setInstanceFollowRedirects(false);connection.setRequestMethod("POST");connection.setDoOutput(true);connection.setRequestProperty("Content-Type","application/json");connection.setFixedLengthStreamingMode(payload.length);try(OutputStream output=connection.getOutputStream()){output.write(payload);}if(connection.getResponseCode()!=200)throw new IOException("电脑未接受内容，请检查配对或内容大小");String response;try(InputStream input=connection.getInputStream()){response=new String(read(input,65536),StandardCharsets.UTF_8);}JSONObject ack=new JSONObject(open(key,response));if(!ack.optBoolean("saved") || !clip.getString("Id").equals(ack.getString("id")))throw new IOException("保存确认不匹配");if(!file.delete())throw new IOException("无法更新待发送列表");count++;}finally{connection.disconnect();}}return count>0 ? "已保存 "+count+" 条到电脑桌面" : "没有待发送内容";}finally{sending.set(false);}}
}
