using System;using System.IO;using System.Drawing;using System.Net;using System.Text;using System.Web.Script.Serialization;
namespace ContentMover { static class MobileTests {
    static void Assert(bool ok,string name){if(!ok)throw new Exception(name);}
    static void CheckRemotePolicy(){
        foreach(string value in new[]{"100.64.0.1","100.90.80.70","100.127.255.254"}){var ip=IPAddress.Parse(value);Assert(MobileServer.Allowed(ip,true),"远程地址范围");Assert(!MobileServer.Allowed(ip,false),"局域网模式拒绝远程地址");}
        foreach(string value in new[]{"100.63.255.255","100.128.0.1","100.100.100.100","8.8.8.8","::1"})Assert(!MobileServer.Allowed(IPAddress.Parse(value),true),"不接受保留或公网地址");
        Assert(MobileServer.Allowed(IPAddress.Parse("192.168.1.2"),false),"保留局域网访问");
        bool rejected=false;using(var remote=new MobileServer(MobileCrypto.NewKey(),null,true)){try{remote.Start(0,IPAddress.Any);}catch(InvalidOperationException){rejected=true;}}Assert(rejected,"远程模式禁止绑定全部网卡");
        var prior=new JavaScriptSerializer().Deserialize<MobileSettings>("{\"Enabled\":true,\"Key\":\"previous-key\"}");Assert(prior.Enabled && !prior.Remote && prior.Key=="previous-key","旧配置保留密钥且远程默认关闭");
    }
    public static void VerifyInterop(string folder){var vector=new JavaScriptSerializer().Deserialize<System.Collections.Generic.Dictionary<string,string>>(File.ReadAllText(Path.Combine(folder,"interop.json")));Assert(MobileCrypto.Open(Convert.FromBase64String(vector["key"]),File.ReadAllText(Path.Combine(folder,"java-envelope.json")))==vector["plain"],"Android → Windows 加密互通");File.WriteAllText(Path.Combine(folder,"interop-test.txt"),"PASS: Android -> Windows production crypto; Unicode and whitespace preserved.");}
    public static void Run(string folder){Directory.CreateDirectory(folder);CheckRemotePolicy();var key=MobileCrypto.NewKey();string sealedText=MobileCrypto.Seal(key,"中文 😀\n空格  ");Assert(MobileCrypto.Open(key,sealedText)=="中文 😀\n空格  ","加密 Unicode 保真");File.WriteAllText(Path.Combine(folder,"interop.json"),new JavaScriptSerializer().Serialize(new{key=Convert.ToBase64String(key),@sealed=sealedText,plain="中文 😀\n空格  "}),new UTF8Encoding(false));bool failed=false;try{MobileCrypto.Open(MobileCrypto.NewKey(),sealedText);}catch{failed=true;}Assert(failed,"错误密钥被拒绝");var store=new MobileStore(Path.Combine(folder,"desktop"),Path.Combine(folder,"state"));string png;using(var image=new Bitmap(12,12))using(var stream=new MemoryStream()){image.Save(stream,System.Drawing.Imaging.ImageFormat.Png);png=Convert.ToBase64String(stream.ToArray());}var clip=new MobileClip{Id=Guid.NewGuid().ToString("N"),Text="原文\n  空格 😀",Title="手机标题",Note="备注 **加粗**"};clip.Images.Add(new MobileImage{Data=png});clip.Images.Add(new MobileImage{Data=png});var json=new JavaScriptSerializer();using(var server=new MobileServer(key,store)){int port=server.Start(0);var client=new WebClient();client.Headers[HttpRequestHeader.ContentType]="application/json";string payload=MobileCrypto.Seal(key,json.Serialize(clip));string response=client.UploadString("http://127.0.0.1:"+port+"/v1/clips",payload);Assert(MobileCrypto.Open(key,response).Contains("\"saved\":true"),"加密确认");string path=OutputFiles.DatedPath(Path.Combine(folder,"desktop"),DateTime.Today);string before=File.ReadAllText(path);client.UploadString("http://127.0.0.1:"+port+"/v1/clips",payload);Assert(File.ReadAllText(path)==before,"重试不会重复追加");Assert(before.Contains(clip.Text) && before.Contains("备注 **加粗**\r\n\r\n!["),"文字与首张图分段");Assert(Directory.GetFiles(Path.Combine(folder,"desktop","assets"+DateTime.Today.ToString("yyyy-M-d"))).Length==2,"多图与日期目录");failed=false;try{client.UploadString("http://127.0.0.1:"+port+"/v1/clips",MobileCrypto.Seal(MobileCrypto.NewKey(),json.Serialize(clip)));}catch(WebException){failed=true;}Assert(failed,"网络错误密钥拒绝");Assert(File.ReadAllText(path)==before,"拒绝消息不修改文件");}File.WriteAllText(Path.Combine(folder,"mobile-test.txt"),"PASS: explicit remote mode; remote bind restriction; LAN compatibility; old settings retained; encrypted transport; authenticated acknowledgement; Unicode; multiple dated images; paragraph separation; duplicate retry; wrong-key rejection; prior content preserved.");}
} }
